# Generated by Django 4.2 on 2023-04-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maincomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentusername', models.CharField(max_length=255)),
                ('commentmessage', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='mainforum',
            old_name='message',
            new_name='postmessage',
        ),
        migrations.RenameField(
            model_name='mainforum',
            old_name='username',
            new_name='postusername',
        ),
    ]
