# Generated by Django 4.2 on 2023-04-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0002_maincomment_rename_message_mainforum_postmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincomment',
            name='commentforpostid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='commentmessage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='commentusername',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
