# Generated by Django 4.2 on 2023-04-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0003_maincomment_commentforpostid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincomment',
            name='commentforpostid',
        ),
        migrations.AddField(
            model_name='maincomment',
            name='commentforpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainforum.mainforum'),
        ),
    ]
