# Generated by Django 4.2 on 2023-04-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0004_remove_maincomment_commentforpostid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainforum',
            name='postid',
        ),
    ]
