# Generated by Django 4.2 on 2023-04-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0005_remove_mainforum_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincomment',
            name='commentforpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainforum.mainforum'),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='commentmessage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maincomment',
            name='commentusername',
            field=models.CharField(max_length=255),
        ),
    ]
