# Generated by Django 4.2 on 2023-04-20 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0006_alter_maincomment_commentforpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainforum',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
