# Generated by Django 4.2 on 2023-04-21 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0007_mainforum_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincomment',
            name='commentdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
