name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Pull new change on hosted container
      run: |
        curl -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"cmd": "pm2 stop 0; killall python3; git fetch; git pull; pm2 start 0", "pwd": "/root/bruhforum"}' https://api.ssh.surf/exec --header 'x-ssh-auth: ${{ secrets.SSH_API_KEY }}'